image: python:rc
cache:
  paths:
    - ~/.cache/pip/

before_script:
  - python -V
  - python -m pip install --upgrade pytest pytest-cov 

tests:
  script:
    - python -m pytest --cov=calculator tests/
